// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRelation = "relations"

// Relation mapped from table <relations>
type Relation struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FollowerID  int64          `gorm:"column:follower_id;not null;index:follower_id,priority:1;comment:关注者id" json:"follower_id"`     // 关注者id
	FollowingID int64          `gorm:"column:following_id;not null;index:following_id,priority:1;comment:被关注者id" json:"following_id"` // 被关注者id
	CreatedAt   *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
