// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:视频id" json:"id"`                       // 视频id
	AuthorID      int64          `gorm:"column:author_id;not null;index:author_id,priority:1;comment:上传用户id" json:"author_id"` // 上传用户id
	Title         string         `gorm:"column:title;not null;comment:视频标题" json:"title"`                                      // 视频标题
	CoverURL      string         `gorm:"column:cover_url;not null;comment:封面url" json:"cover_url"`                             // 封面url
	PlayURL       string         `gorm:"column:play_url;not null;comment:视频播放url" json:"play_url"`                             // 视频播放url
	FavoriteCount int64          `gorm:"column:favorite_count;not null;comment:点赞数" json:"favorite_count"`                     // 点赞数
	CommentCount  int64          `gorm:"column:comment_count;not null;comment:评论数" json:"comment_count"`                       // 评论数
	CreatedAt     *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
