version: "3"

services:
  database:
    container_name: "tuzi_database"
    image: mysql:8.0.31
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: tuzi_tiktok
      MYSQL_ROOT_PASSWORD: "admin"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - /data/tuzi-tiktok/data:/var/lib/mysql
      - /root/tuzi-tiktok/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  nacos:
    container_name: "tuzi_registry"
    image: nacos/nacos-server:v2.2.3
    environment:
      MODE: "standalone"
    ports:
      - "18848:8848"
  oss:
    container_name: "tuzi_oss"
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z.fips
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - /data/tuzi-tiktok/oss:/data
    command: server /data --console-address ":9998" --address ":9090"
    ports:
      - "9998:9998"
  all:
    container_name: "tuzi_tiktok"
    ports:
      - "8888:8888"

networks:
  default:
    external:
      name: tuzi-network