version: "3"

services:
  database:
    container_name: "tuzi_database"
    image: mysql:8.0.31
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: tuzi_tiktok
      MYSQL_ROOT_PASSWORD: "admin"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - /data/tuzi-tiktok/data:/var/lib/mysql
      - /root/tuzi-tiktok/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  nacos:
    container_name: "tuzi_registry"
    image: nacos/nacos-server:v2.2.3
    environment:
      MODE: "standalone"
    ports:
      - "18848:8848"
  oss:
    container_name: "tuzi_oss"
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z.fips
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - /data/tuzi-tiktok/oss:/data
    command: server /data --console-address ":9998" --address ":9090"
    ports:
      - "9998:9998"
  gateway:
    container_name: "tuzi_gateway"
    build:
      context: ./
      dockerfile: DockerfileGateway
    ports:
      - "18888:8888"
    environment:
      TUZI_ENV: docker
  auth:
    container_name: "tuzi_auth"
    build:
      context: ./
      dockerfile: DockerfileAuth
    environment:
      TUZI_ENV: docker
  comment:
    container_name: "tuzi_comment"
    build:
      context: ./
      dockerfile: DockerfileCom
    environment:
      TUZI_ENV: docker
  favorite:
    container_name: "tuzi_favorite"
    build:
      context: ./
      dockerfile: DockerfileFav
    environment:
      TUZI_ENV: docker
  feed:
    container_name: "tuzi_feed"
    build:
      context: ./
      dockerfile: DockerfileFee
    environment:
      TUZI_ENV: docker
  filetransfer:
    container_name: "tuzi_filetransfer"
    build:
      context: ./
      dockerfile: DockerfileFt
    environment:
      TUZI_ENV: docker
  message:
    container_name: "tuzi_message"
    build:
      context: ./
      dockerfile: DockerfileMsg
    environment:
      TUZI_ENV: docker
  publish:
    container_name: "tuzi_publish"
    build:
      context: ./
      dockerfile: DockerfilePub
    environment:
      TUZI_ENV: docker
  relation:
    container_name: "tuzi_relation"
    build:
      context: ./
      dockerfile: DockerfileRel
    environment:
      TUZI_ENV: docker
  debug:
    container_name: debug
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TUZI_ENV: docker

networks:
  default:
    external:
      name: tuzi-network