registry:
  host: "100.93.41.99"
  port: 8848
  namespaceId: "c8bf818f-7660-4590-b763-157cffcd209b"
  group: "DEFAULT_GROUP"
  dataId: "bootstrap.yml"
log:
  level: "Debug"
  development: false
  #   console | json
  encoding: "console"
database:
  #  DSN 优先生效 (如果存在)
  dsn: root:admin@(100.93.41.99:3307)/tuzi_tiktok?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: admin
  host: 100.93.41.99
  port: 3307
  databaseName: tuzi_tiktok
  timeout: 2000
oss:
  #  minio:
  #    endpoint: "phablet:9090"
  #    bucket: tiktok
  #    accessKey: admin
  #    secretKey: minioadmin
  lfs:
    externalURL: "http://100.111.163.99:9092"
    endpoint: "127.0.0.1:9092"
    bucket: tiktok
    storagePath: "E:/Merge/Tuzi-TikTok/lfs"
secret:
  JWTPublicKey: |-
    -----BEGIN EC PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEB5RL++OQZiutQsytDuw/c7xhSpH1
    pGbnRJswMRecPsAl+A7Qu7rFx3oUSGdGjelZAmOf966WB4pU9eiLXIAu8Q==
    -----END EC PUBLIC KEY-----

redis:
  addr: "172.22.110.46:6388"
  password: ""
  db: 0