registry:
  host: "phablet"
  port: 8848
  namespaceId: "c8bf818f-7660-4590-b763-157cffcd209b"
  group: "DEFAULT_GROUP"
  dataId: "bootstrap.yml"
log:
  level: "Debug"
  development: false
  encoding: "json"
database:
  #  DSN 优先生效 (如果存在)
  dsn: root:admin@(localhost:3306)/tuzi_tiktok?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: admin
  host: 127.0.0.1
  port: 3306
  dataBaseName: tuzi_tiktok
  timeout: 2000
