// Code generated by hertz generator.

package feed

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"tuzi-tiktok/gateway/biz/err/access"
	"tuzi-tiktok/gateway/biz/err/global"
	feed "tuzi-tiktok/gateway/biz/model/feed"
	"tuzi-tiktok/gateway/biz/service"
	feed2 "tuzi-tiktok/kitex/kitex_gen/feed"
	"tuzi-tiktok/utils/mapstruct"
)

// GetFeedList .
// @router /douyin/feed/ [GET]
func GetFeedList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedRequest
	var handler = "GetFeedList"
	err = c.Bind(&req)
	if err != nil {
		_ = c.Error(global.RequestParameterBindError.WithHandler(handler).WithWarn(err))
		return
	}

	access.DebugRecordRequest(c, req)

	R, err := service.ServiceSet.Feed.GetFeedList(ctx, &feed2.FeedRequest{
		LatestTime: req.LatestTime,
		Token:      req.Token,
	})
	if err != nil {
		_ = c.Error(global.RPCClientCallError.WithHandler(handler).WithError(err))
		return
	}
	resp := mapstruct.ToFeedResponse(R)
	c.JSON(consts.StatusOK, resp)
}
