// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	auth "tuzi-tiktok/gateway/biz/router/auth"
	comment "tuzi-tiktok/gateway/biz/router/comment"
	favorite "tuzi-tiktok/gateway/biz/router/favorite"
	feed "tuzi-tiktok/gateway/biz/router/feed"
	message "tuzi-tiktok/gateway/biz/router/message"
	publish "tuzi-tiktok/gateway/biz/router/publish"
	relation "tuzi-tiktok/gateway/biz/router/relation"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	favorite.Register(r)

	relation.Register(r)

	publish.Register(r)

	message.Register(r)

	feed.Register(r)

	auth.Register(r)

	comment.Register(r)
}
