// Code generated by hertz generator.

package message

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tuzi-tiktok/gateway/biz/router/control"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		control.Authentication(),
	}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmessagelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
