// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tuzi-tiktok/gateway/biz/err"
)

func main() {
	h := server.Default(server.WithMaxRequestBodySize(1024 * 1024 * 200))
	h.Use(err.ErrorHandlerMiddleware())
	register(h)
	h.Spin()
}
