// Code generated by hertz generator.

package relation

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tuzi-tiktok/gateway/biz/router/control"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		control.Authentication(),
	}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowerlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfriendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
